version: "3.8"
services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
      - render
    environment:
      - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION}
    volumes:
      - ${APPDATA_PATH}/ollama:/root/.ollama
    ports:
      - "11434:11434"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - VECTOR_DB=qdrant
      - QDRANT_URI=http://qdrant:6333
      - QDRANT_API_KEY=
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ${APPDATA_PATH}/openwebui:/app/backend/data
    ports:
      - "3000:8080"
    depends_on:
      - ollama
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - ${APPDATA_PATH}/qdrant/storage:/qdrant/storage
      - ${APPDATA_PATH}/qdrant/snapshots:/qdrant/snapshots
    ports:
      - "6333:6333"
