version: "3.8"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${APPDATA_PATH}/ollama:/root/.ollama
    ports:
      - "11434:11434"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - VECTOR_DB=qdrant
      - QDRANT_URI=http://qdrant:6333
      - QDRANT_API_KEY=
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ${APPDATA_PATH}/openwebui:/app/backend/data
    ports:
      - "3000:8080"
    depends_on:
      - ollama
      - qdrant

  qdrant:
    image: qdrant/qdrant:gpu-nvidia-latest
    container_name: qdrant
    restart: unless-stopped
    runtime: nvidia
    environment:
      - QDRANT__GPU__INDEXING=1
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${APPDATA_PATH}/qdrant/storage:/qdrant/storage
      - ${APPDATA_PATH}/qdrant/snapshots:/qdrant/snapshots
    ports:
      - "6333:6333"
