version: "3.8"
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: unraid
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-routes=${LOCAL_SUBNET}
      - TS_USERSPACE=false
    volumes:
      - ${APPDATA_PATH}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "${HOMEPAGE_PORT}:3000"
    volumes:
      - ${APPDATA_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  unraid-api:
    image: ghcr.io/unraid/unraid-api:latest
    container_name: unraid-api
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - UNRAID_API_URL=${UNRAID_API_URL}
      - UNRAID_API_KEY=${UNRAID_API_KEY}
    ports:
      - "${UNRAID_API_PORT}:3000"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3010:3001"
    volumes:
      - ${APPDATA_PATH}/uptime-kuma:/app/data
    environment:
      - TZ=${TZ}

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TZ}

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
