version: "3.8"

services:
  ollama-rocm:
    image: ollama/ollama:rocm
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-5m}
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    volumes:
      - ${APPDATA_PATH:-/opt/chimera/appdata}/ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.chimera.role == brain
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - qdrant
      - ollama-rocm
    environment:
      - TZ=${TZ:-America/New_York}
      - VECTOR_DB=qdrant
      - QDRANT_URI=http://qdrant:6333
      - OLLAMA_BASE_URL=http://ollama-rocm:11434
      - OPENAI_API_BASE_URL=http://host.docker.internal:8000/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${APPDATA_PATH:-/opt/chimera/appdata}/openwebui:/app/backend/data
    ports:
      - "3000:8080"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.chimera.role == brain
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ${APPDATA_PATH:-/opt/chimera/appdata}/qdrant/storage:/qdrant/storage
      - ${APPDATA_PATH:-/opt/chimera/appdata}/qdrant/snapshots:/qdrant/snapshots
    ports:
      - "6333:6333"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.chimera.role == brain
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    depends_on:
      - qdrant
      - searxng
    environment:
      - TZ=${TZ:-America/New_York}
      - STORAGE_DIR=/app/server/storage
      - VECTOR_DB=qdrant
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - SEARXNG_ENDPOINT=http://searxng:8080
    volumes:
      - ${APPDATA_PATH:-/opt/chimera/appdata}/anythingllm:/app/server/storage
    ports:
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.chimera.role == brain
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  searxng:
    image: searxng/searxng:latest
    environment:
      - TZ=${TZ:-America/New_York}
      - BASE_URL=${SEARXNG_BASE_URL:-http://localhost:8888/}
    volumes:
      - ./brain-config/searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./brain-config/searxng/limiter.toml:/etc/searxng/limiter.toml:ro
    ports:
      - "8888:8080"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.chimera.role == brain
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  wyoming-whisper:
    image: rhasspy/wyoming-whisper:latest
    command: --model medium --language en
    volumes:
      - ${APPDATA_PATH:-/opt/chimera/appdata}/whisper:/data
    ports:
      - "10300:10300"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.chimera.role == brain
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  wyoming-piper:
    image: rhasspy/wyoming-piper:latest
    command: --voice en_US-amy-medium
    volumes:
      - ${APPDATA_PATH:-/opt/chimera/appdata}/piper:/data
    ports:
      - "10200:10200"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.chimera.role == brain
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  default:
    name: chimera-brain
    driver: overlay
